name: Setup Cassandra

on: push

jobs:

  test:
    runs-on: ubuntu-latest

    services:
      cassandra:
        image: cassandra
        ports:
          - 9042:9042

    steps:
      - name: check
        run: |
          docker ps

      - name: Check out Git repository
        uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: '9'

      - name: Install leiningen
        uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.3

      - name: Cache maven
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: m2-${{ hashFiles('project.clj') }}
          restore-keys: |
            m2-

      - name: Test
        run: lein test
